[package]
name = "mmm"
version = "0.4.0"
edition = "2024"

[dependencies]
crossterm = { version = "0.28.1", features = ["event-stream"] }
doubuff = { git = "https://github.com/oranellis/doubuff-rs.git", version = "0.1.5" }
futures = "0.3.31"
tokio = { version = "1.43.0", features = ["macros", "rt-multi-thread", "time"] }

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
